### ISSUE TITLE
Consider adding a full example

### ISSUE THREAD

**Issue by frnmst** [gouravkhunger/jekyll-url-metadata#6]
Hello and thanks for this project.

I think it would be more interesting if potential users are shown an example (or use case). I was able to create simple link previews with a hover effect like this:

![capture](https://github.com/gouravkhunger/jekyll-url-metadata/assets/8964425/f3265968-35c9-453b-a24a-e88657f56c7e)

I made some tweaks to your talk.jekyllrb.com forum reply. This file is called `_includes/link_preview.html`

```html
{% comment %}See https://talk.jekyllrb.com/t/embedding-opengraph-links-in-posts/8124/6{% endcomment %}
{% assign meta = include.url | metadata %}

<div class="link-preview-box">
<a href="{{ include.url }}" title="{{ meta['title'] }}">
  {% if meta['og:image'] and meta['og:image'] != blank %}
  <img src="{{ meta['og:image'] }}" alt="{{ meta['title'] }}">
  {% else %}
  {% comment %}Add a fallback image here, if the opengraph image for given url does not exist. See https://upload.wikimedia.org/wikipedia/commons/f/f5/Antu_edit-image-face-recognize.svg Elegant Alternative Suite for Plasma 5. Antü Plasma-KDE Theme are licensed under the CREATIVE COMMONS BY-SA 3.0.{% endcomment %}
  <img src="/assets/open_graph_default_img.svg" alt="{{ meta['title'] }}">
  {% endif %}

  <p class="link-preview-title">{{ meta['title'] | truncate: site.link_preview.title_max_characters }}</p>
  <p class="link-preview-description">{{ meta['og:description'] | truncate: site.link_preview.description_max_characters }}</p>
</a>
</div>
```

I created a separate CSS file called `_sass/link-preview.scss` that is imported by the main one

```css
.link-preview-box {
    width: 100%;
    border: none;
    padding: 0px;
    margin-top: 8px;
    margin-bottom: 8px;
}

.link-preview-box a {
    font-family: sans-serif;
    border-radius: 4px;
    color: black;
    text-decoration: none;
    background-color: #dddddd;
    padding: 8px;
    display: block;
    top: 0;
    left: 0;
    bottom: 0;
    right: 0;
}

.link-preview-box a:hover {
    background-color: #555;
    color: white;
}

.link-preview-box img {
    width: auto;
    height: auto;
    max-width: 512px;
    max-height: 64px;
}

.link-preview-title {
    font-size: 18px;
}

.link-preview-description {
    font-size: 14px;
    margin: 0;
}
```

Finally, add this to the `_config.yml` file

```yaml
link_preview:
  title_max_characters: 64
  description_max_characters: 128
```

Links are added in the same way you do

```jinja
{% include link_preview.html url="https://git-lfs.com/" %}
```
